#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

wmake $targetType library
wmake $targetType rocketMotor

#-- Compile Utilities --------------------------------------------------------
cd utilities
wmake $targetType postProcessRocket
wmake $targetType mapVolFields
wmake $targetType rocketConservation
wmake $targetType setRocketInitField
